name: Testing

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: "18.x"
      - run: npm ci
      - run: npm run lint
      - run: npm run types
    #   TODO: add tests
    #   - run: npm run test
        env:
          CI: true
      - run: npm run docs
      - run: npm run build
